stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  REGISTRY_URL: registry.gitlab.com/eyabouaziz/projetsb/container_registry
  COMPOSE_IMAGE: $REGISTRY_URL/elecstore:latest # Unified image for the environment
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: elecstore
  MYSQL_USER: user
  MYSQL_PASSWORD: password

build-docker-compose:
  image: docker:24
  stage: build
  services:
    - docker:dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
  script:
    - docker-compose build
    - docker-compose push
  only:
    refs:
      - main
      - tags
