stages:
  - test
  - build


variables:
  DOCKER_DRIVER: overlay2 # Recommended for Docker in Docker to improve performance
  REGISTRY_URL: registry.gitlab.com/eyabouaziz/projetsb/container_registry
  BACKEND_IMAGE: $REGISTRY_URL/backend:latest # Reusable variable for the image name
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: elecstore
  MYSQL_USER: user
  MYSQL_PASSWORD: password
# Test the Angular frontend
test-frontend:
  image: node:20
  stage: test
  before_script:
    - apt-get update && apt-get install -y wget gnupg
    - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
    - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
    - apt-get update && apt-get install -y google-chrome-stable
    - export CHROME_BIN=/usr/bin/google-chrome
    - cd frontend
    - npm ci --legacy-peer-deps
  script:
    - npm run test -- --watch=false --browsers=ChromeHeadless 
  allow_failure: true
  artifacts:
    paths:
      - coverage/ # Save test coverage reports if applicable
    expire_in: 1 week

# Build the Angular frontend and push to Docker registry
build-frontend:
  image: docker:24
  stage: build
  services:
    - docker:dind
  variables:
    FRONTEND_IMAGE: $REGISTRY_URL/frontend:latest # Reusable variable for the image name
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
  script:
    - cd frontend
    - docker build -t $FRONTEND_IMAGE -f Dockerfile .
    - docker push $FRONTEND_IMAGE
