stages:
  - test
  - build

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2 # Recommended for Docker in Docker to improve performance
  REGISTRY_URL: https://gitlab.com/eyabouaziz/projetsb/container_registry
  BACKEND_IMAGE: $REGISTRY_URL/backend:latest # Reusable variable for the image name

test-backend:
  image: maven:3.8.7-openjdk-21
  stage: test
  script:
    - mvn clean test

build-backend:
  image: docker:24
  stage: build
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
  script:
    - docker build -t $BACKEND_IMAGE -f elecstore/Dockerfile .
    - docker push $BACKEND_IMAGE
