stages:
  - test
  - build

services:
  - docker:dind
  - mysql:8.0

variables:
  DOCKER_DRIVER: overlay2 # Recommended for Docker in Docker to improve performance
  REGISTRY_URL: registry.gitlab.com/eyabouaziz/projetsb/container_registry
  BACKEND_IMAGE: $REGISTRY_URL/backend:latest # Reusable variable for the image name
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: elecstore
  MYSQL_USER: user
  MYSQL_PASSWORD: password

test-backend:
  image: openjdk:21-jdk-slim
  stage: test
  services:
  - mysql:8.0
  before_script:
    - apt-get update && apt-get install -y default-mysql-client
    - echo "Waiting for database to be ready..."
    - until mysqladmin ping -h "mysql" --silent; do echo "Waiting for MySQL..."; sleep 1; done
    - mysql -h mysql -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE < database/electronics.sql
  script:
    - apt-get update && apt-get install -y maven && rm -rf /var/lib/apt/lists/*
    - cd elecstore
    - mvn clean test

build-backend:
  image: docker:24
  stage: build
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
  script:
    - cd elecstore
    - docker build -t $BACKEND_IMAGE -f Dockerfile .
    - docker push $BACKEND_IMAGE
