version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: elecstore-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: elecstore
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./database/elecstore.sql:/docker-entrypoint-initdb.d/elecstore.sql
