version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: elecstore-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: elecstore
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./database/electronics.sql:/docker-entrypoint-initdb.d/electronics.sql

  backend:
    build:
      context: .
      dockerfile: elecstore/Dockerfile.backend
    image: docker.io/eyabouaziz/backend:latest
    container_name: elecstore-backend
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://elecstore-db:3306/elecstore
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8090"
    depends_on:
      - db
    networks:
      - elecstore-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    image: docker.io/eyabouaziz/frontend:latest
    container_name: elecstore-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - elecstore-network

networks:
  elecstore-network:
    driver: bridge
